name: knit
description: A tool for managing kubernetes manifests with KCL
inputs:
  filepath:
    description: "File to render"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/tvandinther/knit:v0.0.3"
  args:
    - ${{ inputs.filepath }}
