package helm

const chartFileContent = `"""
This file was generated by knit. DO NOT EDIT.
To update the repository or version of this chart, re-run the 'knit add helm' command.
"""

schema Chart:
    repository: "%s" = "%s"
    name: "%s" = "%s"
    version: "%s" = "%s"
    values: Values = Values{}
`
