name: Build Artifacts

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build for ${{ matrix.arch }}
        run: |
          mkdir -p build
          GOOS=linux GOARCH=${{ matrix.arch }} scripts/build.sh ${{ github.events.inputs.tag }}
          tar -czf build/knit-${{ matrix.arch }}.tar.gz knit

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: knit-${{ matrix.arch }}
          path: dist/knit-${{ matrix.arch }}.tar.gz
