name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: version
        run: |
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Trigger Build Workflow
        uses: actions/checkout@v3

      - name: Call Build Workflow
        uses: ./.github/workflows/build.yml
        with:
          version: ${{ steps.version.outputs.version }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-amd64
          path: build/amd64/

      - name: Download Build Artifacts (arm64)
        uses: actions/download-artifact@v3
        with:
          name: build-arm64
          path: build/arm64/

      - name: Create Release
        run: |
          gh release create "${{ steps.version.outputs.version }}" build/** --title "${{ steps.version.outputs.version }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
