name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ github.ref_name }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: version
        run: |
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Trigger Build Workflow
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: build/
          merge-multiple: true

      - name: Create Release
        run: |
          gh release create "${{ steps.version.outputs.version }}" build/** --title "${{ steps.version.outputs.version }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
