name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Action - Render
        uses: ./
        with:
          filepath: example/main.k

      - name: Check output
        run: cat rendered/example.yaml
